config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :orders
  resources :products
  resources :brands
  resources :shops
  
  	# sessions
	get 'login' => 'sessions#new', as: 'login'
	post 'sessions/create' => 'sessions#create', as: 'create_session'
	get 'logout' => 'sessions#destroy', as: 'logout'

	# Users
  	resources :users

  	# API Stuff
	namespace :api, :defaults => {:format => :json} do

		# Users
		post 'login' => 'users#login'
		resources :users

		# Orders
		resources :orders

		# Products
		get 'products/ean/:ean' => 'products#getProductFromEAN'
		resources :products

	end

	root 'pages#index'
end

app/models/shop.rb
class Shop < ApplicationRecord
	has_and_belongs_to_many :employees, class_name: :User, join_table: "shop_employees"
	has_and_belongs_to_many :reps, class_name: :User, join_table: "shop_reps"
	has_many :orders
	has_many :sold_products, through: :orders, source: :products

	def get_points
		points = 0	
		self.sold_products.each do |product| 
			points += product.points
		end 
		return points
	end

	def get_top_product

		productCountMap = Hash.new
		self.sold_products.each do |product|

			productCount = productCountMap[product.id]
			if (productCount) 
				productCountMap[product.id] = productCount + 1
			else 
				productCountMap[product.id] = 1
			end
		end

		maxCount = 0
		maxProductID = nil
		productCountMap.each do |key, value|

			if value > maxCount 
				maxCount = value
				maxProductID = key
			end
		end

		if maxProductID.nil? 
			return nil
		else 
			return {"product" => Product.find(maxProductID), "count" => maxCount}
		end
	end




	def get_top_employee

		sql = "SELECT u.*
			   FROM users u 
			   JOIN shop_employees se ON u.id = se.user_id
			   WHERE u.points = (SELECT MAX(u.points)
             					 FROM users u  
             					 JOIN shop_employees se ON u.id = se.user_id   
             					 WHERE se.shop_id = #{self.id})"

      results = ActiveRecord::Base.connection.execute(sql)
      return results.to_json

	end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: [:show, :edit, :update, :destroy]

  # GET /shops
  # GET /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1
  # GET /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    @shop = Shop.new
  end

  # GET /shops/1/edit
  def edit
  end

  # POST /shops
  # POST /shops.json
  def create
    @shop = Shop.new(shop_params)

    respond_to do |format|
      if @shop.save
        format.html { redirect_to @shop, notice: 'Shop was successfully created.' }
        format.json { render :show, status: :created, location: @shop }
      else
        format.html { render :new }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shops/1
  # PATCH/PUT /shops/1.json
  def update
    respond_to do |format|
      if @shop.update(shop_params)
        format.html { redirect_to @shop, notice: 'Shop was successfully updated.' }
        format.json { render :show, status: :ok, location: @shop }
      else
        format.html { render :edit }
        format.json { render json: @shop.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shops/1
  # DELETE /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: 'Shop was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shop_params
      params.require(:shop).permit(:name, :account_number, :location)
    end
end

app/helpers/shops_helper.rb
module ShopsHelper

  def get_rep_name_link(shop)
    if shop.reps.count != 0
      link_to shop.reps.first.first_name + ' ' + shop.reps.first.last_name, shop.reps.first
    else
      'No rep specified'
    end
  end

end

app/views/shops/_form.html.erb
<%= form_with(model: shop, local: true) do |form| %>
  <% if shop.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shop.errors.count, "error") %> prohibited this shop from being saved:</h2>

      <ul>
      <% shop.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :account_number %>
    <%= form.text_field :account_number %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shops/edit.html.erb
<h1>Editing Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Show', @shop %> |
<%= link_to 'Back', shops_path %>

app/views/shops/index.html.erb
<p id="notice"><%= notice %></p>



<div class="container">

<h1>Shops</h1>
<%= link_to 'New Shop', new_shop_path, class: 'btn btn-primary float-right' %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th class="text-center">Account number</th>
      <th class="text-center">Location</th>
      <th class="text-center">Total Shop points</th>
      <th class="text-center">Shop Rep</th>
      
    </tr>
  </thead>

  <tbody>
    <% @shops.each do |shop| %>
      <tr>
        <td><%= link_to shop.name, shop %></td>
        <td class="text-center"><%= shop.account_number %></td>
        <td class="text-center"><%= shop.location %></td>
        <td class="text-center"><%= shop.get_points %></td>
        <td class="text-center"><%= get_rep_name_link(shop) %></td>
        <!-- <td><%#= link_to 'Edit', edit_shop_path(shop) %></td> -->
        <!-- <td><%#= link_to 'Destroy', shop, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

<br>


</div>

app/views/shops/new.html.erb
<h1>New Shop</h1>

<%= render 'form', shop: @shop %>

<%= link_to 'Back', shops_path %>

app/views/shops/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
	<div class="row">
		<div class="col-9">
			<h1><%= @shop.name %></h1>
		</div>
		<div class="col-3">
			<ul class="list-group">
				<li class="list-group-item">Account #: <%= @shop.account_number %></li>
				<li class="list-group-item">Location: <%= @shop.location %></li>
				<li class="list-group-item">Shop Rep: <%= get_rep_name_link(@shop) %></li>

			</ul>
		</div>
	</div>
</div>

<div class="container">
	<div class="row">
		<div class="col-12">
			<ul class="list-group list-group-horizontal " style="margin:20px auto;">
				<li class="list-group-item">
					<h3 class="text-center top-dash">Total Shop Points</h3>
					<h1 class="text-center"><%= @shop.get_points %></h1>
				</li>
				<li class="list-group-item">
					<h3 class="text-center top-dash">Total Items Sold</h3>
					<h1 class="text-center"><%= @shop.sold_products.count %></h1>
				</li>
				<li class="list-group-item">
					<h3 class="text-center top-dash">Top Seller</h3>
					
						<% top_product = @shop.get_top_product %>

						<% if top_product %>
						<h1 class="text-center"> </h1>
							<h4 class="text-center">
								<strong>
									<%= @shop.get_top_product["product"].name %>
								</strong> 
								<br ><%= @shop.get_top_product["count"] %> have been sold
							</h4>
						<% else %>

							<p>No products have been sold</p>

						<% end %>
						
				</li>
				<li class="list-group-item">
					<h3 class="text-center top-dash">Top Employee NI</h3>
					<% if @shop.reps.count != 0 %>
						<h1 class="text-center"><%= @shop.employees.first.first_name %></h1>
					<% elsif %>
						<h3 class="text-center top-dash">Shop Rep: No Employee</h1>
					<% end %>
				</li>

			</ul>
		</div>
	</div>
</div>

<div class="container">



	<table class="table table-striped">
		<thead>
			<th>Product Name</th>
			<th>EAN</th>
			<th>Product Points</th>

		</thead>
		<% @shop.sold_products.each do |sold_product| %>
			<tr>
				<td><%= sold_product.name %></td>
				<td><%= sold_product.ean %></td>
				<td><%= sold_product.points %></td>
			</tr>
		<% end %>

	</table>
</div>




<%= link_to 'Edit', edit_shop_path(@shop) %> |
<%= link_to 'Back', shops_path %>